[package]
name = "asa"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
colored = "3.0.0"
crossterm = "0.29.0"
log = "0.4.27"
simple_logger = { version = "5.0.0", default-features = false, features = ["colors"] }
unescape = "0.1.0"
